#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#ifndef APP_TIMER_V2
#define APP_TIMER_V2
#endif // APP_TIMER_V2

#ifndef APP_TIMER_V2_RTC1_ENABLED
#define APP_TIMER_V2_RTC1_ENABLED
#endif // APP_TIMER_V2_RTC1_ENABLED

#ifndef NRFX_SYSTICK_ENABLED
#define NRFX_SYSTICK_ENABLED 1
#endif // NRFX_SYSTICK_ENABLED

#endif // APP_CONFIG_H